# $NetBSD$

DISTNAME=	docopt-0.6.2
PKGNAME=	python-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=d/docopt/}

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	http://docopt.org/
COMMENT=	Pythonic command line arguments parser
LICENSE=	mit

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../eliteraspberries/python-setuptools/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
