# $NetBSD$

DISTNAME=	pip-21.3.1
PKGNAME=	python-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pip/}
DIST_SUBDIR=	pip

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	https://pip.pypa.io/
COMMENT=	The PyPA recommended tool for installing Python packages
LICENSE=	mit

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../eliteraspberries/python-setuptools/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
