# $NetBSD$

DISTNAME=	pefile-2019.4.18
PKGNAME=	python-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pefile/}

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	https://github.com/erocarrera/pefile
COMMENT=	Python PE parsing module
LICENSE=	mit

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../eliteraspberries/python-future/buildlink3.mk"
.include "../../eliteraspberries/python-setuptools/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
