# $NetBSD$

DISTNAME=	numpy-1.13.3
PKGNAME=	python-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_PYPI:=n/numpy/}
EXTRACT_SUFX=	.zip

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	http://www.numpy.org/
COMMENT=	Python numerical computing package
LICENSE=	original-bsd

USE_LANGUAGES=	c

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../eliteraspberries/python-setuptools/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
