# $NetBSD$

DISTNAME=	msgpack-0.6.2
PKGNAME=	python-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=m/msgpack/}

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	https://msgpack.org/
COMMENT=	MessagePack is an efficient binary serialization format
LICENSE=	apache-2.0

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../eliteraspberries/python-setuptools/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
