# $NetBSD$

DISTNAME=	pyinstaller-hooks-contrib-2021.3
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pyinstaller-hooks-contrib/}

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	https://github.com/pyinstaller/pyinstaller-hooks-contrib
COMMENT=	Community maintained hooks for PyInstaller
LICENSE=	apache-2.0 AND gnu-gpl-v2

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../eliteraspberries/python-setuptools/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
