# $NetBSD$

DISTNAME=	dis3-0.1.3
PKGNAME=	python-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=d/dis3/}

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	https://github.com/KeyWeeUsr/dis3
COMMENT=	Python 2.7 backport of the "dis" module from Python 3.5+
LICENSE=	mit

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../eliteraspberries/python-setuptools/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
