# $NetBSD$
# used by eliteraspberries/python/Makefile
# used by eliteraspberries/python-setuptools/Makefile
# used by eliteraspberries/python-wheel/Makefile
# used by eliteraspberries/python-numpy/Makefile
# used by eliteraspberries/cython/Makefile
# used by eliteraspberries/python-pillow/Makefile
# used by eliteraspberries/python-docopt/Makefile
# used by eliteraspberries/python-pyglet/Makefile
# used by eliteraspberries/pyinstaller/Makefile

.include "../../eliteraspberries/python/Makefile.version"

PLIST_SUBST+=	PYTHON_MAJOR_VERSION=${PYTHON_MAJOR_VERSION}
PLIST_SUBST+=	PYTHON_BASEVER=${PYTHON_BASEVER}
PLIST_SUBST+=	PYTHON_VERSION=${PYTHON_VERSION}

CPPFLAGS+=	-DPyMem_Malloc=malloc
CPPFLAGS+=	-DPyMem_Realloc=realloc
CPPFLAGS+=	-DPyMem_Free=free
CPPFLAGS+=	-DPyObject_MALLOC=malloc
CPPFLAGS+=	-DPyObject_REALLOC=realloc
CPPFLAGS+=	-DPyObject_FREE=free
