# $NetBSD$

META_PACKAGE=	yes

PKGNAME=	python-3
PKGREVISION=	4
CATEGORIES=	lang

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	https://www.python.org/
COMMENT=	Python programming language
LICENSE=	python-software-foundation

.include "../../eliteraspberries/python38/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
