# $NetBSD$

DISTNAME=	meson-1.8.3
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=mesonbuild/}
GITHUB_RELEASE=	${PKGVERSION_NOREV}

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	https://mesonbuild.com/
COMMENT=	The Meson build system
LICENSE=	apache-2.0

.include "../../eliteraspberries/ninja/buildlink3.mk"
.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../eliteraspberries/python-setuptools/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
