# $NetBSD$

DISTNAME=	pyglet-1.2.4
PKGNAME=	python-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pyglet/}

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	http://pyglet.org/
COMMENT=	Cross-platform windowing and multimedia library for Python
LICENSE=	original-bsd

USE_LANGUAGES=	# none

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python-setuptools/buildlink3.mk"
.include "../../eliteraspberries/python-setuptools/setuppy.mk"
.include "../../mk/bsd.pkg.mk"
