# $NetBSD$

DISTNAME=	pyglet-1.3.3
PKGNAME=	python-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pyglet/}
EXTRACT_SUFX=	.zip

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	http://pyglet.org/
COMMENT=	Cross-platform windowing and multimedia library for Python
LICENSE=	original-bsd

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../eliteraspberries/python-future/buildlink3.mk"
.include "../../eliteraspberries/python-setuptools/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
