# $NetBSD$

.if !defined(CMAKE_MK)
CMAKE_MK:=

.if empty(PKG_OPTIONS:Mdebug)
# CMAKE_ARGS+=	-DCMAKE_BUILD_TYPE=Release
.else
CMAKE_ARGS+=	-DCMAKE_BUILD_TYPE=Debug
CMAKE_ARGS+=	-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
.endif
CMAKE_ARGS+=	-DCMAKE_C_FLAGS="${CPPFLAGS} ${CFLAGS}"
CMAKE_ARGS+=	-DCMAKE_CXX_FLAGS="${CPPFLAGS} ${CXXFLAGS}"
CMAKE_ARGS+=	-DCMAKE_SHARED_LINKER_FLAGS="${LDFLAGS}"
CMAKE_ARGS+=	-DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}"
CMAKE_ARGS+=	-DCMAKE_INSTALL_PREFIX="${PREFIX}"
CMAKE_ARGS+=	-DCMAKE_INSTALL_MANDIR="${PKGMANDIR}"
CMAKE_ARGS+=	-DCMAKE_INSTALL_INFODIR="${PKGINFODIR}"

.include "../../mk/bsd.prefs.mk"

CMAKE_ARGS+=	-DCMAKE_BUILD_RPATH="${BUILDLINK_DIR}/lib"
CMAKE_ARGS+=	-DCMAKE_INSTALL_RPATH="${PREFIX}/lib"
.if ${OPSYS} == "Darwin"
# CMAKE_ARGS+=	-DCMAKE_MACOSX_RPATH="FALSE"
# CMAKE_ARGS+=	-DCMAKE_INSTALL_NAME_DIR="${PREFIX}/lib"
CMAKE_ARGS+=	-DCMAKE_MACOSX_RPATH="TRUE"
CMAKE_ARGS+=	-DCMAKE_BUILD_WITH_INSTALL_NAME_DIR="TRUE"
CMAKE_ARGS+=	-DCMAKE_INSTALL_NAME_DIR="@rpath"
.endif

CMAKE_DIR=			build

do-configure:
	mkdir -p ${WRKSRC}/${CMAKE_DIR}
	cd ${WRKSRC}/${CMAKE_DIR} && env ${MAKE_ENV} cmake ${CMAKE_ARGS} ..

BUILD_DIRS=			${CMAKE_DIR}

do-build:
	cd ${WRKSRC}/${CMAKE_DIR} && \
	for x in ${BUILD_TARGET}; do \
		env ${MAKE_ENV} DESTDIR=${DESTDIR} \
			cmake --build . --target $${x}; \
	done

do-install:
	cd ${WRKSRC}/${CMAKE_DIR} && \
	for x in ${INSTALL_TARGET}; do \
		env ${MAKE_ENV} DESTDIR=${DESTDIR} \
			cmake --build . --target $${x}; \
	done

.include "../../eliteraspberries/cmake/buildlink3.mk"
BUILDLINK_DEPMETHOD.cmake= build

.endif # CMAKE_MK
