# $NetBSD$

DISTNAME=	packaging-23.2
PKGNAME=	python-${DISTNAME}
# PKGREVISION=	2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=p/packaging/}
EXTRACT_SUFX=	.tar.gz

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	https://github.com/pypa/packaging
COMMENT=	Core utilities for Python packages
LICENSE=	mit

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/pip.mk"
.include "../../mk/bsd.pkg.mk"
