# $NetBSD$

DISTNAME=		SCons-${PKGVERSION_NOREV}
PKGNAME=		scons-4.7.0
CATEGORIES=		devel
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=scons/scons/${PKGVERSION_NOREV}/}
EXTRACT_SUFX=	.tar.gz

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	http://scons.org/
COMMENT=	Software construction tool
LICENSE=	isc

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../mk/bsd.pkg.mk"
