# $NetBSD$

DISTNAME=	scons-3.1.2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=scons/}

MAINTAINER=	mansourmoufid@gmail.com
HOMEPAGE=	http://scons.org/
COMMENT=	Software construction tool
LICENSE=	isc

.include "../../eliteraspberries/python/buildlink3.mk"
.include "../../eliteraspberries/python/setuppy.mk"
.include "../../mk/bsd.pkg.mk"
